version: "3.7"
services:

  app:
    build:
      args:
        user: diego
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - project

  nginx:
    image: nginx:1.17-alpine
    container_name: project-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - project

networks:
  project:
    driver: bridge